services:
- type: web
  name: nocodb
  env: docker
  autoDeploy: false
  healthCheckPath: /dashboard
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: nocodbDB
      property: connectionString
  - key: PORT
    value: 8080
databases:
- name: nocodbDB
